#!/usr/bin/bash

SITE="https://meet.jit.si"
echo "Waiting for $SITE to be up:"
until curl -sSf --head --request GET "$SITE" >/dev/null
do
        :
done
echo "Up"

export NO_COLOR=1
deno run --allow-net --allow-read "$HOME/dsl-meet/web_server/web_server.js" &

echo "Waiting for local web server to be up:"
until curl -k -sSf --head --request GET "https://localhost" >/dev/null
do
        :
done
echo "Up"

exec startx
